import React, { useState, useRef } from 'react';
import { Printer, ChevronDown, ChevronUp, BookOpen, MessageSquare, Heart, Bookmark, X, Download, FileText } from 'lucide-react';
import { useTranslation } from 'react-i18next';

const FullStudyGuideView = ({ studyGuide, onClose }) => {
  const { t, i18n } = useTranslation();
  const [expandedVerses, setExpandedVerses] = useState(new Set());
  const [expandAll, setExpandAll] = useState(true);
  const printRef = useRef(null);
  const zh = i18n.language === 'zh' || i18n.language.startsWith('zh');

  const safeString = (value) => typeof value === 'string' ? value : '';
  const safeArray = (value) => Array.isArray(value) ? value : [];

  const toggleVerse = (index) => {
    setExpandedVerses((prev) => {
      const next = new Set(prev);
      if (next.has(index)) {
        next.delete(index);
      } else {
        next.add(index);
      }
      return next;
    });
  };

  const toggleExpandAll = () => {
    if (expandAll) {
      setExpandedVerses(new Set());
    } else {
      setExpandedVerses(new Set(safeArray(studyGuide.exegesis).map((_, i) => i)));
    }
    setExpandAll(!expandAll);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleMarkdownExport = () => {
    let md = `# ${safeString(studyGuide.title)}\n\n`;
    md += `**${zh ? '经文' : 'Passage'}:** ${safeString(studyGuide.passage)}  \n`;
    md += `**${zh ? '神学立场' : 'Theology'}:** ${safeString(studyGuide.theology)}\n\n---\n\n`;

    if (studyGuide.overview) {
      md += `## ${zh ? '概览' : 'Overview'}\n\n`;
      if (studyGuide.overview.introduction) md += `### ${zh ? '简介' : 'Introduction'}\n\n${safeString(studyGuide.overview.introduction)}\n\n`;
      if (studyGuide.overview.historicalContext) md += `### ${zh ? '历史背景' : 'Historical Context'}\n\n${safeString(studyGuide.overview.historicalContext)}\n\n`;
      if (studyGuide.overview.literaryContext) md += `### ${zh ? '文学背景' : 'Literary Context'}\n\n${safeString(studyGuide.overview.literaryContext)}\n\n`;
    }

    if (exegesis.length > 0) {
      md += `## ${zh ? '逐节解经' : 'Verse-by-Verse Exegesis'}\n\n`;
      for (const verse of exegesis) {
        md += `### ${safeString(verse.verse)}\n\n`;
        if (verse.text) md += `> *${safeString(verse.text)}*\n\n`;
        md += `${safeString(verse.explanation)}\n\n`;
        const insights = safeArray(verse.keyInsights);
        if (insights.length > 0) {
          md += `**${zh ? '关键洞察' : 'Key Insights'}:**\n`;
          for (const insight of insights) md += `- ${safeString(insight)}\n`;
          md += `\n`;
        }
        const refs = safeArray(verse.crossReferences);
        if (refs.length > 0) md += `**${zh ? '参考经文' : 'Cross References'}:** ${refs.map(safeString).join(', ')}\n\n`;
        md += `---\n\n`;
      }
    }

    const questions = safeArray(studyGuide.discussionQuestions);
    if (questions.length > 0) {
      md += `## ${zh ? '讨论问题' : 'Discussion Questions'}\n\n`;
      questions.forEach((q, i) => { md += `${i + 1}. ${safeString(q)}\n`; });
      md += `\n`;
    }

    if (studyGuide.lifeApplication) {
      md += `## ${zh ? '生活应用' : 'Life Application'}\n\n`;
      for (const [key, label] of [['practicalApplications', zh ? '实际应用' : 'Practical Applications'], ['reflectionPoints', zh ? '反思要点' : 'Reflection Points'], ['actionSteps', zh ? '行动步骤' : 'Action Steps']]) {
        const items = safeArray(studyGuide.lifeApplication[key]);
        if (items.length > 0) {
          md += `### ${label}\n\n`;
          for (const item of items) md += `- ${safeString(item)}\n`;
          md += `\n`;
        }
      }
    }

    const commentaries = safeArray(studyGuide.commentariesUsed);
    if (commentaries.length > 0) {
      md += `## ${zh ? '使用的注释书' : 'Commentaries Used'}\n\n`;
      for (const c of commentaries) {
        md += `- ${safeString(c.citation)} **${safeString(c.name)}** by ${safeString(c.author)}`;
        if (c.url) md += ` — [source](${c.url})`;
        md += `\n`;
      }
    }

    md += `\n---\n\n*${zh ? '由圣经学习指南生成器生成' : 'Generated by Bible Study Guide Generator'}*\n`;

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const filename = (studyGuide.passage || 'study-guide').replace(/[:\s]/g, '_').replace(/[^\w\u4e00-\u9fff_-]/g, '');
    a.download = `${filename}.md`;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url); }, 100);
  };

  const exegesis = safeArray(studyGuide.exegesis);

  return (
    <div className="fixed inset-0 z-50 overflow-auto bg-gray-900/60 dark:bg-black/70 backdrop-blur-sm" onClick={onClose}>
      <div
        className="max-w-4xl mx-auto my-8 bg-white dark:bg-gray-900 rounded-2xl shadow-2xl overflow-hidden print:shadow-none print:rounded-none print:m-0 print:max-w-none"
        onClick={(e) => e.stopPropagation()}
        ref={printRef}
      >
        {/* Header */}
        <div className="sticky top-0 z-10 bg-indigo-600 dark:bg-indigo-800 text-white p-6 print:bg-white print:text-black print:border-b-2 print:border-gray-800">
          <div className="flex items-center justify-between print:hidden">
            <div>
              <h1 className="text-2xl font-bold">{safeString(studyGuide.title) || (zh ? '学习指南' : 'Study Guide')}</h1>
              <p className="text-indigo-200 dark:text-indigo-300 mt-1">
                {safeString(studyGuide.passage)} — {safeString(studyGuide.theology)} {zh ? '立场' : 'Perspective'}
              </p>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={handleMarkdownExport}
                className="p-2 bg-white/20 hover:bg-white/30 rounded-lg transition-colors"
                title={zh ? '导出Markdown' : 'Export Markdown'}
              >
                <FileText className="w-5 h-5" />
              </button>
              <button
                onClick={handlePrint}
                className="p-2 bg-white/20 hover:bg-white/30 rounded-lg transition-colors"
                title={zh ? '打印' : 'Print'}
              >
                <Printer className="w-5 h-5" />
              </button>
              <button
                onClick={onClose}
                className="p-2 bg-white/20 hover:bg-white/30 rounded-lg transition-colors"
                title={zh ? '关闭' : 'Close'}
              >
                <X className="w-5 h-5" />
              </button>
            </div>
          </div>
          {/* Print-only header */}
          <div className="hidden print:block">
            <h1 className="text-2xl font-bold text-center">{safeString(studyGuide.title)}</h1>
            <p className="text-center text-gray-600 mt-1">
              {safeString(studyGuide.passage)} — {safeString(studyGuide.theology)}
            </p>
          </div>
        </div>

        <div className="p-6 space-y-8">
          {/* Overview */}
          <section>
            <h2 className="text-xl font-bold text-gray-800 dark:text-gray-100 mb-4 flex items-center gap-2">
              <BookOpen className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
              {t('overview')}
            </h2>
            <div className="space-y-4 text-gray-700 dark:text-gray-300">
              {studyGuide.overview?.introduction && (
                <div>
                  <h3 className="font-semibold text-gray-800 dark:text-gray-200">{t('introduction')}</h3>
                  <p className="mt-1 leading-relaxed">{safeString(studyGuide.overview.introduction)}</p>
                </div>
              )}
              {studyGuide.overview?.historicalContext && (
                <div>
                  <h3 className="font-semibold text-gray-800 dark:text-gray-200">{t('historicalContext')}</h3>
                  <p className="mt-1 leading-relaxed">{safeString(studyGuide.overview.historicalContext)}</p>
                </div>
              )}
              {studyGuide.overview?.literaryContext && (
                <div>
                  <h3 className="font-semibold text-gray-800 dark:text-gray-200">{t('literaryContext')}</h3>
                  <p className="mt-1 leading-relaxed">{safeString(studyGuide.overview.literaryContext)}</p>
                </div>
              )}
            </div>
          </section>

          {/* Verse-by-Verse Exegesis */}
          <section>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-xl font-bold text-gray-800 dark:text-gray-100 flex items-center gap-2">
                <Bookmark className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                {t('exegesis')}
                <span className="text-sm font-normal text-gray-500 dark:text-gray-400">
                  ({exegesis.length} {zh ? '节' : exegesis.length === 1 ? 'verse' : 'verses'})
                </span>
              </h2>
              <button
                onClick={toggleExpandAll}
                className="text-sm text-indigo-600 dark:text-indigo-400 hover:text-indigo-800 dark:hover:text-indigo-300 flex items-center gap-1 transition-colors print:hidden"
              >
                {expandAll ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                {expandAll ? (zh ? '全部收起' : 'Collapse all') : (zh ? '全部展开' : 'Expand all')}
              </button>
            </div>

            <div className="space-y-3">
              {exegesis.map((verse, index) => {
                const isExpanded = expandAll || expandedVerses.has(index);
                return (
                  <div
                    key={index}
                    className="border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden print:border-none print:border-b print:border-gray-300 print:rounded-none"
                  >
                    <button
                      onClick={() => toggleVerse(index)}
                      className="w-full flex items-center justify-between p-4 text-left hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors print:hover:bg-transparent print:cursor-default"
                    >
                      <div className="flex items-start gap-3">
                        <span className="flex-shrink-0 w-8 h-8 flex items-center justify-center bg-indigo-100 dark:bg-indigo-900/50 text-indigo-700 dark:text-indigo-300 text-sm font-bold rounded-full">
                          {index + 1}
                        </span>
                        <div>
                          <p className="font-semibold text-indigo-600 dark:text-indigo-400">
                            {safeString(verse.verse)}
                          </p>
                          {verse.text && (
                            <p className="text-sm text-gray-600 dark:text-gray-400 italic mt-1 line-clamp-2 print:line-clamp-none">
                              "{safeString(verse.text)}"
                            </p>
                          )}
                        </div>
                      </div>
                      <ChevronDown
                        className={`w-5 h-5 text-gray-400 transition-transform print:hidden ${isExpanded ? 'rotate-180' : ''}`}
                      />
                    </button>

                    {(isExpanded || true) && (
                      <div
                        className={`transition-all duration-200 ${isExpanded ? 'max-h-[2000px] opacity-100' : 'max-h-0 opacity-0 overflow-hidden'} print:max-h-none print:opacity-100`}
                      >
                        <div className="px-4 pb-4 pt-0 border-t border-gray-100 dark:border-gray-700">
                          <div className="pl-11 space-y-3">
                            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">{safeString(verse.explanation)}</p>

                            {safeArray(verse.keyInsights).length > 0 && (
                              <div>
                                <h4 className="text-sm font-semibold text-gray-600 dark:text-gray-400 mb-1">
                                  {zh ? '💡 关键洞察' : '💡 Key Insights'}
                                </h4>
                                <ul className="list-disc list-inside text-sm text-gray-600 dark:text-gray-400 space-y-1">
                                  {safeArray(verse.keyInsights).map((insight, i) => (
                                    <li key={i}>{safeString(insight)}</li>
                                  ))}
                                </ul>
                              </div>
                            )}

                            {safeArray(verse.crossReferences).length > 0 && (
                              <div>
                                <h4 className="text-sm font-semibold text-gray-600 dark:text-gray-400 mb-1">
                                  {zh ? '📖 参考经文' : '📖 Cross References'}
                                </h4>
                                <p className="text-sm text-indigo-600 dark:text-indigo-400">
                                  {safeArray(verse.crossReferences).map(safeString).join(' • ')}
                                </p>
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </section>

          {/* Discussion Questions */}
          {safeArray(studyGuide.discussionQuestions).length > 0 && (
            <section>
              <h2 className="text-xl font-bold text-gray-800 dark:text-gray-100 mb-4 flex items-center gap-2">
                <MessageSquare className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                {t('discussionQuestions')}
              </h2>
              <ol className="list-decimal list-inside space-y-3 text-gray-700 dark:text-gray-300">
                {safeArray(studyGuide.discussionQuestions).map((q, i) => (
                  <li key={i} className="leading-relaxed pl-2">
                    {safeString(q)}
                  </li>
                ))}
              </ol>
            </section>
          )}

          {/* Life Application */}
          {studyGuide.lifeApplication && (
            <section>
              <h2 className="text-xl font-bold text-gray-800 dark:text-gray-100 mb-4 flex items-center gap-2">
                <Heart className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                {zh ? '生活应用' : 'Life Application'}
              </h2>
              <div className="space-y-4">
                {safeArray(studyGuide.lifeApplication.practicalApplications).length > 0 && (
                  <div>
                    <h3 className="font-semibold text-gray-800 dark:text-gray-200 mb-2">
                      {zh ? '实际应用' : 'Practical Applications'}
                    </h3>
                    <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 space-y-1">
                      {safeArray(studyGuide.lifeApplication.practicalApplications).map((app, i) => (
                        <li key={i}>{safeString(app)}</li>
                      ))}
                    </ul>
                  </div>
                )}
                {safeArray(studyGuide.lifeApplication.reflectionPoints).length > 0 && (
                  <div>
                    <h3 className="font-semibold text-gray-800 dark:text-gray-200 mb-2">
                      {zh ? '反思要点' : 'Reflection Points'}
                    </h3>
                    <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 space-y-1">
                      {safeArray(studyGuide.lifeApplication.reflectionPoints).map((pt, i) => (
                        <li key={i}>{safeString(pt)}</li>
                      ))}
                    </ul>
                  </div>
                )}
                {safeArray(studyGuide.lifeApplication.actionSteps).length > 0 && (
                  <div>
                    <h3 className="font-semibold text-gray-800 dark:text-gray-200 mb-2">
                      {zh ? '行动步骤' : 'Action Steps'}
                    </h3>
                    <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 space-y-1">
                      {safeArray(studyGuide.lifeApplication.actionSteps).map((step, i) => (
                        <li key={i}>{safeString(step)}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            </section>
          )}

          {/* Additional Resources */}
          {studyGuide.additionalResources && (
            <section>
              <h2 className="text-xl font-bold text-gray-800 dark:text-gray-100 mb-4">
                {zh ? '📚 其他资源' : '📚 Additional Resources'}
              </h2>
              <div className="space-y-3">
                {safeArray(studyGuide.additionalResources.memoryVerses).length > 0 && (
                  <div>
                    <h3 className="font-semibold text-gray-800 dark:text-gray-200 mb-1">{zh ? '背诵经文' : 'Memory Verses'}</h3>
                    <p className="text-gray-700 dark:text-gray-300">{safeArray(studyGuide.additionalResources.memoryVerses).join(', ')}</p>
                  </div>
                )}
                {safeArray(studyGuide.additionalResources.prayerPoints).length > 0 && (
                  <div>
                    <h3 className="font-semibold text-gray-800 dark:text-gray-200 mb-1">{zh ? '祷告要点' : 'Prayer Points'}</h3>
                    <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 space-y-1">
                      {safeArray(studyGuide.additionalResources.prayerPoints).map((pt, i) => (
                        <li key={i}>{safeString(pt)}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            </section>
          )}

          {/* Commentaries Used */}
          {safeArray(studyGuide.commentariesUsed).length > 0 && (
            <section className="border-t border-gray-200 dark:border-gray-700 pt-6">
              <h2 className="text-lg font-bold text-gray-800 dark:text-gray-100 mb-3">{t('commentariesUsed')}</h2>
              <div className="space-y-2">
                {safeArray(studyGuide.commentariesUsed).map((commentary, i) => (
                  <div key={i} className="text-sm text-gray-600 dark:text-gray-400">
                    <span className="font-semibold text-indigo-600 dark:text-indigo-400">
                      {safeString(commentary.citation)}
                    </span>{' '}
                    {safeString(commentary.name)} by {safeString(commentary.author)}
                    {commentary.url && (
                      <a
                        href={commentary.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="ml-2 text-blue-500 hover:underline text-xs"
                      >
                        [source]
                      </a>
                    )}
                  </div>
                ))}
              </div>
            </section>
          )}
        </div>
      </div>
    </div>
  );
};

export default FullStudyGuideView;
