/**
 * Generate a Markdown string from a studyGuide object and trigger a client-side download.
 * No backend endpoint needed.
 */
export function exportStudyGuideAsMarkdown(studyGuide, lang = 'en') {
  if (!studyGuide) return;

  const lines = [];
  const isZh = lang.startsWith('zh');

  // Title
  lines.push(`# ${studyGuide.title || (isZh ? '圣经学习指南' : 'Bible Study Guide')}`);
  lines.push('');
  lines.push(`**${isZh ? '经文' : 'Passage'}:** ${studyGuide.passage || ''}`);
  lines.push(`**${isZh ? '神学立场' : 'Theological Perspective'}:** ${studyGuide.theology || ''}`);
  lines.push('');

  // Overview
  if (studyGuide.overview) {
    lines.push(`## ${isZh ? '概览' : 'Overview'}`);
    lines.push('');
    if (studyGuide.overview.introduction) {
      lines.push(`### ${isZh ? '简介' : 'Introduction'}`);
      lines.push(studyGuide.overview.introduction);
      lines.push('');
    }
    if (studyGuide.overview.historicalContext) {
      lines.push(`### ${isZh ? '历史背景' : 'Historical Context'}`);
      lines.push(studyGuide.overview.historicalContext);
      lines.push('');
    }
    if (studyGuide.overview.literaryContext) {
      lines.push(`### ${isZh ? '文学背景' : 'Literary Context'}`);
      lines.push(studyGuide.overview.literaryContext);
      lines.push('');
    }
  }

  // Exegesis
  if (studyGuide.exegesis?.length) {
    lines.push(`## ${isZh ? '逐节解经' : 'Verse-by-Verse Exegesis'}`);
    lines.push('');
    studyGuide.exegesis.forEach((v) => {
      lines.push(`### ${v.verse}`);
      if (v.text) lines.push(`> "${v.text}"`);
      lines.push('');
      if (v.explanation) lines.push(v.explanation);
      lines.push('');
      if (v.keyInsights?.length) {
        lines.push(`**${isZh ? '关键洞察' : 'Key Insights'}:**`);
        v.keyInsights.forEach((ins) => lines.push(`- ${ins}`));
        lines.push('');
      }
      if (v.verbatimQuotes?.length) {
        lines.push(`**${isZh ? '注释书引用' : 'Commentary Quotes'}:**`);
        v.verbatimQuotes.forEach((q) => {
          lines.push(`> "${q.quote}"`);
          lines.push(`> — ${q.author}, *${q.commentary}*`);
          lines.push('');
        });
      }
      if (v.crossReferences?.length) {
        lines.push(`**${isZh ? '参考经文' : 'Cross References'}:** ${v.crossReferences.join(' • ')}`);
        lines.push('');
      }
    });
  }

  // Discussion Questions
  if (studyGuide.discussionQuestions?.length) {
    lines.push(`## ${isZh ? '讨论问题' : 'Discussion Questions'}`);
    lines.push('');
    studyGuide.discussionQuestions.forEach((q, i) => {
      lines.push(`${i + 1}. ${q}`);
    });
    lines.push('');
  }

  // Life Application
  if (studyGuide.lifeApplication) {
    lines.push(`## ${isZh ? '生活应用' : 'Life Application'}`);
    lines.push('');
    if (studyGuide.lifeApplication.practicalApplications?.length) {
      lines.push(`### ${isZh ? '实际应用' : 'Practical Applications'}`);
      studyGuide.lifeApplication.practicalApplications.forEach((a) => lines.push(`- ${a}`));
      lines.push('');
    }
    if (studyGuide.lifeApplication.reflectionPoints?.length) {
      lines.push(`### ${isZh ? '反思要点' : 'Reflection Points'}`);
      studyGuide.lifeApplication.reflectionPoints.forEach((r) => lines.push(`- ${r}`));
      lines.push('');
    }
    if (studyGuide.lifeApplication.actionSteps?.length) {
      lines.push(`### ${isZh ? '行动步骤' : 'Action Steps'}`);
      studyGuide.lifeApplication.actionSteps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
      lines.push('');
    }
  }

  // Additional Resources
  if (studyGuide.additionalResources) {
    lines.push(`## ${isZh ? '其他资源' : 'Additional Resources'}`);
    lines.push('');
    if (studyGuide.additionalResources.crossReferences?.length) {
      lines.push(`**${isZh ? '参考经文' : 'Cross References'}:** ${studyGuide.additionalResources.crossReferences.join(' • ')}`);
      lines.push('');
    }
    if (studyGuide.additionalResources.memoryVerses?.length) {
      lines.push(`**${isZh ? '背诵经文' : 'Memory Verses'}:** ${studyGuide.additionalResources.memoryVerses.join(' • ')}`);
      lines.push('');
    }
    if (studyGuide.additionalResources.prayerPoints?.length) {
      lines.push(`**${isZh ? '祷告要点' : 'Prayer Points'}:**`);
      studyGuide.additionalResources.prayerPoints.forEach((p) => lines.push(`- ${p}`));
      lines.push('');
    }
  }

  // Commentaries Used
  if (studyGuide.commentariesUsed?.length) {
    lines.push(`## ${isZh ? '使用的注释书' : 'Commentaries Used'}`);
    lines.push('');
    studyGuide.commentariesUsed.forEach((c) => {
      lines.push(`- **${c.citation || ''}** ${c.name} by *${c.author}*${c.url ? ` — [source](${c.url})` : ''}`);
    });
    lines.push('');
  }

  lines.push('---');
  lines.push(isZh ? '由圣经学习指南生成器生成' : 'Generated by Bible Study Guide Generator');

  const markdown = lines.join('\n');

  // Client-side download
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const safeName = (studyGuide.passage || 'study-guide')
    .replace(/[:\s]/g, '_')
    .replace(/[^\w\u4e00-\u9fff_-]/g, '')
    .replace(/_+/g, '_')
    .replace(/^_|_$/, '');
  a.href = url;
  a.download = `${safeName}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
